### ISSUE TITLE
Clean-up names (using Aliases?)

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-data-dictionary-viewer#30]
This may not be that simple... but ideally cleanup names. E.g. HydrantMaintenanceInspection > Hydrant Maintenance Inspection

![image](https://user-images.githubusercontent.com/50338557/57641306-8ed74800-7569-11e9-80ec-61625cb6a05c.png)

**Comment by gslyer** [comment]
@previnWong Is this a possible change?

**Comment by previnWong** [comment]
Changed to use alias name.

One thing to note though is that in the relationship object.  The names does not match table alias
relationship object
![image](https://user-images.githubusercontent.com/11183838/72574097-b57a1b00-387c-11ea-98ca-5a01141470e3.png)
![image](https://user-images.githubusercontent.com/11183838/72574240-39340780-387d-11ea-833d-92226be41c1f.png)

table object
![image](https://user-images.githubusercontent.com/11183838/72574116-c32fa080-387c-11ea-9f99-76cd1402f9b0.png)


I cannot add spaces in the relationship card, because I cannot assume when a space happens.  I could check for a capitalization of letters, but I cannot assume a user followed camel case format. So i had to leave it.

I can still link from the relationship card to the other cards, but I strip spaces and lowercase everything to do comparison, so that direction works.
